remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Jaewon's Website
logo: /img/Jaewon.jpg
description: CS Ph.D Candidate @ Georgia Institute of Technology
show_downloads: False

include:
  - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"

# Add links with icons
header_links:
  - title: '<i class="fab fa-google-scholar"></i>'
    url: https://scholar.google.com/citations?user=7_u7PNEAAAAJ&hl=en
  - title: '<i class="fab fa-linkedin"></i>'
    url: https://www.linkedin.com/in/jaewon-lee-7ba96aa/
  - title: '<i class="fab fa-github"></i>'
    url: https://github.com/jaewon-lee-github
